version: '3.9'

services:
  api:
    build: .
    container_name: api-llm
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: llm_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    env_file: .env
    ports:
      - "${WAHA_PORT}:${WAHA_PORT}"

volumes:
  pgdata:
